---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-deployment
spec:
  template:
    spec:
      containers:
      - name: ref
        env:
        - name: ENV
          value: "dev"
        - name: GPU_ENABLED
          value: "1"
      