---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3-deployment
spec:
  template:
    spec:
      containers:
      - name: ms3
        env:
        - name: ENV
          value: "dev"
        - name: GPU_ENABLED
          value: "1"
      