---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-deployment
  annotations:
    codefresh.io/app: trade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade
  template:
    metadata:
      labels:
        app: trade
    spec:
      containers:
      - name: trade
        imagePullPolicy: Always
        image: docker.io/kostiscodefresh/simple-env-app:1.0
        ports:
        - containerPort: 8080
